### ISSUE TITLE
Custom error data is lost during reporting.

### ISSUE THREAD

**Issue by alexlatchford** [bugsnag/bugsnag-node#101]
I'm trying to use `onBeforeNotify` to attach metaData as described here: https://docs.bugsnag.com/platforms/nodejs/restify-coffee/customizing-error-reports/

I've made a custom error type (a subclass of `Ajv.ValidationError`) and I'd like to be able to attach the specific JSON validation errors and the value context. My code for that is something like:

```javascript
function onBeforeNotify(notification) {
    // Catch any JSON schema validation errors and send them along too
    const validationExceptions = notification.events[0].exceptions
        .map((exception) => {
            if (exception instanceof ValidationError) {
                return {
                    errors: exception.errors,
                    value: exception.value
                };
            }
            return null;
        })
        .filter(Boolean);

    // Only add metaData for ValidationErrors
    if (validationExceptions.length <= 0) return;

    notification.events[0].metaData.validation = { exceptions: validationExceptions };
}
```

The problem is before `onBeforeNotify` get's there this line is called: https://github.com/bugsnag/bugsnag-node/blob/master/lib/bugsnag.js#L103

This calls [this method](https://github.com/bugsnag/bugsnag-node/blob/master/lib/error.js#L55) which clobbers all custom data 😒 

Should be a pretty quick fix to just copy across all custom error parameters to the new error object. Any chance of a fix?

Thanks,
Alex

PS. Even better would be that this data is automatically attached to the report (as I expected before I embarked on this work..).

**Comment by alexlatchford** [comment]
Just extended this implementation to be more generic:

```

function onBeforeNotify(notification) {
    // Catch any JSON schema validation errors and send them along too
    const exceptions = notification.events[0].exceptions
        .map((exception) => {
            const errorPropNames = Object.getOwnPropertyNames(exception);
            // These come with all errors
            const defaultErrorPropNames = ['message', 'stack'];
            const hasNonDefaultErrorProps = errorPropNames
                .find(errorPropName => !defaultErrorPropNames.includes(errorPropName));
            // Only add an "Exceptions" tab to Bugsnag if we have extra metadata.
            if (hasNonDefaultErrorProps !== undefined) {
                // Ensure we copy all the error props, should be useful!
                return errorPropNames.reduce((acc, propName) => Object.assign(
                        acc,
                        { [propName]: exception[propName] }
                    ), {});
            }
            return null;
        })
        .filter(Boolean);

    // Only add metaData for ValidationErrors
    if (exceptions.length <= 0) return;

    // eslint-disable-next-line no-param-reassign
    notification.events[0].metaData = notification.events[0].metaData || {};
    // eslint-disable-next-line no-param-reassign
    notification.events[0].metaData.Exceptions = exceptions;
}
```

Should in theory copy across all custom error props to an "Exceptions" tab. Next to make a PR to fix the underlying issue!

**Comment by kattrali** [comment]
Thanks for the report, @alexlatchford. I've looked at your proposed solution as well.

Ideally, the solution would allow users to use custom objects while not attaching data which they don't want. I think we could simplify this somewhat to provide the original error object as the second parameter to `onBeforeNotify`. So potential usage would be something like:

```js
function onBeforeNotify(notification, error) {
    if (error instanceof ValidationError) {
        // update notification metadata
    }
}

```

Does that meet your use case? I might be misunderstanding somewhat.

**Comment by alexlatchford** [comment]
Works fine by me. If you take a look at the PR I've raised I went down a different approach to actually include custom error metadata by default so you wouldn't even need to implement an `onBeforeNotify` call. Not sure exactly what the use case would be for filtering CustomEvent metadata but I'm sure that can be tacked onto the approach I outlined in the PR.

**Comment by kattrali** [comment]
That's true. I was only concerned in the case that a validation error or other custom error would include some user information which might need to be removed and erred on the side of sending too little data. 🤔

**Comment by alexlatchford** [comment]
That's true and your call, for us it wouldn't matter too much often errors are un-debuggable (or uneven un-triage-able) without context  so was trying to think of the easiest way to greedily grab as much as possible. Can work backwards from there, guess it depends on how you feel the defaults should be 😄 

FYI: From my experience it's been pretty tricky (compared to my previous experience with Python on Raygun) to get up and running on Bugsnag without automatic context injection. The integration process has taken significantly longer as a result.

**Comment by kattrali** [comment]
Gotcha! The use case makes a lot more sense to me now. :) I've nearly drafted a proposal changeset for how this should work and some new documentation.
