### ISSUE TITLE
Batching errors sent to bugsnag

### ISSUE THREAD

**Issue by ilaif** [bugsnag/bugsnag-node#117]
Hey guys,
You have a terrific service.

### Expected behavior
When many errors are being notified, or many .notify() calls are being made, the library should batch the requests per some time frame (a few seconds) and notification count to optimize network traffic and load on the node.js server.

### Observed behavior
Diving into the source code, every .notify() call sends a request to the bugsnag server, which is highly inefficient (In case there are 50 errors per second, they better be batched into one request and then sent).

### Steps to reproduce
See above.

### Version
v2.0.0

Cheers and thanks in advance,
Ilai

**Comment by kattrali** [comment]
Thanks for the report, @ilaif. Batching makes a lot of sense, and probably a bit of intelligent throttling as well. This is something we should resolve as we are working on a major revision of the library. Do you have any thoughts, @bengourley?

**Comment by bengourley** [comment]
Absolutely agree. Our API already supports sending multiple errors in a
single payload so we should be able to support batching reasonably soon.
We're already working on deduping/throttling too.

**Comment by ilaif** [comment]
I might have some time to contribute an initial PR for this feature until the weekend. Will it be of use?

**Comment by bengourley** [comment]
This is something we're going to be working on ourselves in the near future. The last thing we'd want to do is have you spend time on this and end up it being not used, or replaced by what we do. Thank you for the offer though, it's very kind of you. And also if you feel that this is urgent for you, don't let this stop you from forking the module and making changes per your requirements for now.

**Comment by bengourley** [comment]
Closing this off as this package is now deprecated. ([@bugsnag/js](https://github.com/bugsnag/bugsnag-js/) is our new "universal" notifier for Browser and Node JS).

Batching error reports is on our internal roadmap for the new combined notifier.
