### ISSUE TITLE
Can't disable logs

### ISSUE THREAD

**Issue by alejandromagnorsky** [bugsnag/bugsnag-node#121]
Hello. Can you provide an option to disable logs in the console? I find this to be pretty annoying considering the amount of information being displayed and also because I handle logs by myself.

Thanks.

**Comment by bengourley** [comment]
You can pass in a custom logger object when you configure Bugsnag:

```js
Bugsnag.configure({ logger: <custom logger> })
```

As long as it matches the interface in https://github.com/bugsnag/bugsnag-node/blob/master/lib/logger.js, anything will do, e.g:

```js
function noop() {}
var silentLogger = { info: noop, warn: noop, error: noop }
Bugsnag.configure({ logger: silentLogger })
```

Or you could hook it up with whatever logger you're using in your application e.g. [`bunyan`](https://github.com/trentm/node-bunyan), [`pino`](https://github.com/pinojs/pino) etc…


```js
var bunyan = require('bunyan');
var logger = bunyan.createLogger({ name: 'myapp' })
Bugsnag.configure({ logger: logger })
```

```js
var logger = require('pino')()
Bugsnag.configure({ logger: logger })
```

**Comment by alejandromagnorsky** [comment]
That worked nicely. 
Just to confirm, this does not affect the errors sent to Bugsnag dashboard, right?

Thank you.

**Comment by bengourley** [comment]
Correct
