### ISSUE TITLE
Missing functionality or documentation for app type feature

### ISSUE THREAD

**Issue by CTOJoe** [bugsnag/bugsnag-node#126]
### Expected behavior
Ability to configure `app type` like other platforms. ( [PHP](https://docs.bugsnag.com/platforms/php/other/configuration-options/#app-type) | [GO](https://docs.bugsnag.com/platforms/go/other/configuration-options/#apptype) | [JAVA](https://docs.bugsnag.com/platforms/java/other/configuration-options/#setapptype) | [RUBY](https://docs.bugsnag.com/platforms/ruby/other/configuration-options/#app_type) )

### Observed behavior
Unable to find in [source](https://github.com/bugsnag/bugsnag-node/blob/a5020641b2b84d11169ec7972a25437d6d9d19b7/lib/configuration.js#L44) or [bugsnag documentation](https://docs.bugsnag.com/platforms/nodejs/other/configuration-options/) on how to configure it.

**Comment by bengourley** [comment]
Thanks for the report, we should add this. In the mean time you can add a before notify callback to achieve the desired result:

```js
bugsnag.onBeforeNotify(function (notification, originalError) {
  if (!notification.events[0].app) {
    notification.events[0].app = {}
  }
  notification.events[0].app.type = 'worker' // etc.
})
```
