### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by apexskier** [bugsnag/bugsnag-node#135]
### Expected behavior
Server side code that's been transpiled with a sourcemap will be shown in the bugsnag web interface as the original code.

### Observed behavior
No sourcemap support

### Version
2.2.0

**Comment by bengourley** [comment]
Hi @apexskier. We don't currently support source maps for node projects but this is on our roadmap.

**Comment by bengourley** [comment]
Source maps on Node are now supported by the "universal" JS notifier we just released: [@bugsnag/js](https://github.com/bugsnag/bugsnag-js/). We will be upgrading our tooling soon, as right now `bugsnag-sourcemaps` will be a bit fiddly for Node projects – but source map resolution is enabled on payloads sent from the new notifier.
