### ISSUE TITLE
 Bugsnag:  Error: uv_signal_start EINVAL

### ISSUE THREAD

**Issue by doron2402** [bugsnag/bugsnag-node#136]
### Expected behavior
It shouldn't break my app

### Steps to reproduce
```
Bugsnag:  Error: uv_signal_start EINVAL
 exports._errnoException (util.js:1022:11)
 process.<anonymous> (internal/process.js:206:15)
 emitTwo (events.js:106:13)
 process.emit (events.js:191:7)
 _addListener (events.js:226:14)
 process.addListener (events.js:275:10)
 Object.<anonymous> (...../server.js:181:4)
 Module._compile (module.js:570:32)
 Object.Module._extensions..js (module.js:579:10)
 Module.load (module.js:487:32)
 tryModuleLoad (module.js:446:12)
 Function.Module._load (module.js:438:3)
 Module.runMain (module.js:604:10)
 run (bootstrap_node.js:394:7)
 startup (bootstrap_node.js:149:9)
 bootstrap_node.js:509:3
```
### Version
2.2.0

### Additional information
no

**Comment by doron2402** [comment]
It seems like the bug occurs when listening to `SIGINT` or `SIGTERM` events

**Comment by Cawllec** [comment]
Hi @doron2402, thanks for the report, I'll have a look into this.

**Comment by Cawllec** [comment]
I've had a quick look and this error occurs in newer Node versions if you're attempting to capture `SIGKILL` or `SIGSTOP` signals and certain others in specific scenarios as described in [the process docs](https://nodejs.org/api/process.html#process_signal_events).  

Are you sure you haven't got any `process.on` calls for capturing `SIGKILL` or `SIGSTOP` instances?

**Comment by doron2402** [comment]
Hi @Cawllec,
It's happen when I was trying to capture ` SIGINT` or `SIGTERM`
btw I'm using node version 6.9.4

**Comment by Cawllec** [comment]
So I've tried out an example on 6.9.4 and it's not throwing that error with `SIGTERM` or `SIGINT`, only `SIGKILL` and `SIGSTOP`.  Does the issue persist if you disable or remove Bugsnag?

**Comment by Cawllec** [comment]
Hi @doron2402, from testing we believe that trace you're seeing is simple Bugsnag logging the unhandled error caused by the capture attempt.  While we're not entirely sure why that error would be  occurring when capturing `SIGTERM` and `SIGINT`, we don't believe Bugsnag is actively causing the issue.

If you've got a code sample that reproduces the issue we can have a bit more of a look into it, and we're also going to review the logger to ensure it's clear in the future when a log occurs.

**Comment by Cawllec** [comment]
For reference, we've reproduced the behaviour using the following script and `SIGKILL` but it doesn't cause the issue with `SIGTERM` or `SIGINT`.
```
var bugsnag = require('bugsnag').register('ababababababa')
process.on('SIGKILL', () +> { console.log('SIGKILL') })
```

**Comment by doron2402** [comment]
Cool, thanks for testing it.
I'll close the issue.
Thanks.
