### ISSUE TITLE
not able to minify using create-react-app webpack configuration

### ISSUE THREAD

**Issue by gauravsoti1** [bugsnag/bugsnag-node#138]
### Expected behavior
I install bugsnag using npm install bugsnag --save and when I run npm run build, it should give me minified code.
### Observed behavior
I get an error Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
 	./node_modules/bugsnag/lib/sessions/session.js:29

Read more here: http://bit.ly/2tRViJ9

### Steps to reproduce
npm install bugsnag
npm run build (create-react-app production webpack configuration )

### Version
2.3.0

I fixed it by using 2.0.0 version.

**Comment by bengourley** [comment]
Hi @gauravsoti1. It looks like you want the [`bugsnag-js`](https://github.com/bugsnag/bugsnag-js) libarary if you want to do error handling it in the browser. This repo is for server-side usage in Node.js. Give that a go and let me know if that fixes your problem!

**Comment by gauravsoti1** [comment]
Hello @bengourley, I am using express for server side rendering and using the create-react-app production config for bundling my react code. 

Please check this link: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by bengourley** [comment]
Hey!

When running in a server environment you mustn't run `bugsnag-js` - it simply won't work. Take a look at [this related issue](https://github.com/bugsnag/bugsnag-js/issues/326#issuecomment-368045501) and [this one](https://github.com/bugsnag/bugsnag-react/issues/4) for more information and similar advice.

Likewise, when running browser code you mustn't run `bugsnag-node` (which is just `bugsnag` on npm).

In the future we want to combine the node/browser notifiers into a single universal notifier to alleviate problems like this… but for now you just need to make sure you load the correct module depending on the environment.

Thanks!

**Comment by gauravsoti1** [comment]
@bengourley I get that but the problem was that create-react-app config wasn't able to minify the the bugsnag code from the latest library because it doesn't ship with es5 code I believe.

**Comment by aftabnaveed** [comment]
We are using busnag for a universal REACTJS application and having exactly the same issue.

**Comment by gauravsoti1** [comment]
+aftabnaveed Use webpackIgnorePlugin and ignore bugsnag from your client build. It should be used on server side.
