### ISSUE TITLE
bugsnag-node depends on "unlicensed" code

### ISSUE THREAD

**Issue by kylef** [bugsnag/bugsnag-node#142]
The bugsnag@2.3.1 package depends on various other packages which do not have valid licenses. This makes it hard to install bugsnag legally as in doing so you'd be making possibly illegal copies of the dependencies. Some declare that they follow the MIT license in package.json, but as they do not include a copyright notice in the NPM package it would be against the license to make a copy (such as when a user ran `npm install bugsnag`) which doesn't contain the copyright notice.

I've listed all of the dependencies that I spotted which do not have a valid license and opened issues or PRs on the respective packages:

- [ ] backo@1.1.0 (MIT) - missing copyright notice
    - Filed https://github.com/segmentio/backo/issues/8
- [x] browser-fingerprint@0.0.1 (MIT) - missing full license text
    - I am not sure where the source repository is, the NPM package doesn't mention (https://www.npmjs.com/package/browser-fingerprint)
- [x] node-fingerprint@0.0.2 (MIT) - missing full license text
    - I am not sure where the source repository is, the NPM package doesn't mention (https://www.npmjs.com/package/node-fingerprint)

NOTE, maybe a good idea to use something like [FOSSA](https://fossa.io) which can be setup in CI for all bugsnag libraries. This will check the licensing status of the entire dependency tree.

**Comment by bengourley** [comment]
This module is now deprecated, closing off this issue.
