### ISSUE TITLE
Please upgrade `request` dependency to ^2.87.0

### ISSUE THREAD

**Issue by aforty** [bugsnag/bugsnag-node#145]
Hi!

tl;dr; is it possible to get `request` dependency version pushed up to `^2.87.0`? (currently `^2.81.0`)

I'm trying to sue `rollup` with a project using bugsnag. Bugsnag relies on `request` which relies on `aws-sign2`. The version of `aws-sign2` used by `request@2.81.0` has a bug where it double exports a function and rollup doesn't like that. It has been fixed and the latest version of `request` depends on the fixed version of `aws-sign2`.

So I'd like for the `request` package dependency to be updated so that I can use `rollup` with my project. 😄

**Comment by bengourley** [comment]
You should be able to install the version of request that you want on your project and provided it matches bugsnag's semver range (which `2.87.0` does) it should use that. Any version `v2.x.x` will satisfy `^2.81.0`. Try this and let me know how you get on!

**Comment by aforty** [comment]
Thanks that solved it.
