### ISSUE TITLE
Cannot read property 'startSession' of undefined on test environment

### ISSUE THREAD

**Issue by hems** [bugsnag/bugsnag-node#148]
This is the error that is happening on my test environment:
````
TypeError: Cannot read property 'startSession' of undefined
    at Object.Bugsnag.startSession (...../node_modules/bugsnag/lib/bugsnag.js:317:37)
    at Bugsnag.requestHandler (...../node_modules/bugsnag/lib/bugsnag.js:206:35)
    at Layer.handle [as handle_request] (...../node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (...../node_modules/express/lib/router/index.js:317:13)
    at ...../node_modules/express/lib/router/index.js:284:7
    at Function.process_params (...../node_modules/express/lib/router/index.js:335:12)
    at next (...../node_modules/express/lib/router/index.js:275:10)
````

On the beginning of my server initialization code i have this:

![image](https://user-images.githubusercontent.com/27327/41321956-42677d8c-6e9e-11e8-8506-98ee3b7ad4c4.png)

and on my http server i have this:
![image](https://user-images.githubusercontent.com/27327/41321977-5f3a47be-6e9e-11e8-8a4e-610a8ba755ff.png)

I would expect BugSnag to be completely bypassed because the current ENV is "test"  but turns out it still work?

Before having the setup like this i was not calling ````.register```` on my test environment and i was getting even more errors.

How can i disable bugsnag during the tests?

node version is 10.4.0 running on Ubuntu x64

**Comment by bengourley** [comment]
Hi @hems, I can't exactly see why you would get the error `TypeError: Cannot read property 'startSession' of undefined` but I can see some problems with your setup which you should correct, and see if the problem goes away…

Lines 5 and 6 of your server configuration `bugsnag.releaseStage = …` and `bugsnag.notifyReleaseStage = …` are not how to configure those options, they need to be passed as in an object to the second argument of `bugsnag.register`, plus the `notifyReleaseStages` argument is missing the last `s`. It should be something like this:

```js
bugsnag.register(process.env.BUGSNAG_API_KEY, {
  releaseStage: 'test',
  notifyReleaseStages: [ 'production', 'development' ]
})
```

Let me know how you get on with that. Cheers!

**Comment by hems** [comment]
my bad, those fixed completely did the trick. 
thanks a lot
