### ISSUE TITLE
Sessions tracking against `production`, not configured releaseStage

### ISSUE THREAD

**Issue by CPWeaver** [bugsnag/bugsnag-node#149]
### Expected behavior
Sessions should be tracked against the configured releaseStage

### Observed behavior
Sessions are tracked against the proper appVersion but appear to count against `production`

### Steps to reproduce
Configure with a releaseStage, turn on auto session tracking, observe that sessions are not tracked against the configured stage

### Version
2.4.2

### Additional information
None

Please let me know if I've done something wrong!

**Comment by bengourley** [comment]
Thanks for the report, @CPWeaver! No you haven't done anything wrong – this is a bug in the notifier. We'll schedule a fix.

Cheers!

**Comment by CPWeaver** [comment]
awesome, thanks for the help @bengourley! when I should look for a release?

**Comment by bengourley** [comment]
I just released this – v2.4.3. Let me know whether it fixes your issue. Cheers!
