### ISSUE TITLE
How to add bugsnag middleware to apollo-server-lambda

### ISSUE THREAD

**Issue by marcusx** [bugsnag/bugsnag-node#152]
Can you update your docs or give me an example how to add bugsnag as a middleware to apollo-server-lambda? 

As it is express running in the background I tried to follow [Bugsnag Install Express Middleware](https://docs.bugsnag.com/platforms/nodejs/express/#3-install-middleware) and [Apollo Middleware](https://www.apollographql.com/docs/apollo-server/essentials/server.html#middleware) but I am not getting it working.

**Comment by bengourley** [comment]
Hi @marcusx 👋

We don't have an example for this right now. If Apollo is compatible with Express you should just be able to set Bugsnag up per the docs you linked to. Is there a specific problem you are having? If so feel free to go into more detail here or send an email to support@bugsnag.com.

We did have a few issues around how serverless environments and frameworks differ slightly from traditional servers – take a look at the [search results here](https://github.com/bugsnag/bugsnag-node/search?q=lambda&type=Issues) – but they were simple to resolve. It's entirely possible that we need to do something specific to support Apollo though.

Let us know if you get this working, or what your blockers are! Thanks
