### ISSUE TITLE
bugsnag catches should.js asserts

### ISSUE THREAD

**Issue by matejkramny** [bugsnag/bugsnag-node#37]
As part of node.js testing, mocha and should.js throw exceptions when something fails..

That is expected, apart from the fact that bugsnag tries to catch them :P.

Is it possible to disable bugsnag entirely, while not having to comment out all the `require('bugsnag')` lines?

I tried setting the bugsnag like this:

```
bugsnag.register({
	apiKey: 'a key',
	notifyReleaseStages: ["production"],
	releaseStage: 'development',
	autoNotify: false,
	onUncaughtError: function () {}
});
```

It still catches the errors, which is really annoying.

I temporarily added return statements to each bugsnag function, which helped.

**Comment by ConradIrwin** [comment]
Hey @matejkramny,

Sorry for the slow reply.

In our tests we do this, which helps for cases where we are manually catching and sending to bugsnag. Hopefully that will work for you too.

```
require('bugsnag').notify = function (e) {
  throw e;
}
```

Usually this isn't a problem, as the test runner catches errors first. But sometimes in async callbacks this comes in handy.

**Comment by matejkramny** [comment]
Hi Conrad, thanks for looking at this and fixing it. Interesting behaviour
hehe
