### ISSUE TITLE
Support for multiple Bugsnag projects

### ISSUE THREAD

**Issue by emmettnicholas** [bugsnag/bugsnag-node#43]
The Ruby notifier supports multiple projects:

> If you want to divide errors into multiple Bugsnag projects, you can specify the API key as a parameter to Bugsnag.notify:

https://bugsnag.com/docs/notifiers/ruby#multiple-projects

But the node.js notifier doesn't seem to support this. It would be great to be able to to do something like

    bugsnag.notify(err, {
        apiKey: 'other-api-key-here'
    });

**Comment by AlicanC** [comment]
`bugsnag` should actually be a constructor so we can:
```javascript
var Bugsnag = require('bugsnag');

var one = new Bugsnag('key1');
var two = new Bugsnag('key2');

one.notify(...);
two.notify(...);
```

**Comment by flushentitypacket** [comment]
Stumbled on this trying to figure out how to notify a second Bugsnag project from a single Rails app. The link in OP doesn't seem to point to the right place anymore--is this still a feature in the Ruby lib?

**Comment by flushentitypacket** [comment]
Found the option in the source:
https://github.com/bugsnag/bugsnag-ruby/blob/f4c9f1e47d098331a53a63ca38f4a904a6d0d13e/lib/bugsnag/notification.rb#L64

```ruby
Bugsnag.notify(e, { api_key: 'foo' })
```
