### ISSUE TITLE
Bugsnag.requestHandler(req, res, next) should reset the metaData

### ISSUE THREAD

**Issue by mathieug** [bugsnag/bugsnag-node#52]
Currently, I don't see how to handle metaData with ExpressJS.
I've a middleware `loadUser` set on some routes (which means user needs to be authenticated to access the route). If I put data into metaData in a request then I get a crash in a second request, notify will send data left from the first request.

**Comment by mathieug** [comment]
I guess we should have a global metaData and a metaData per request.

**Comment by ConradIrwin** [comment]
Hey @mathieug!

Thanks for this, there is actually already a metaData-per-request, it just wasn't properly exposed. I've now fixed this, https://github.com/bugsnag/bugsnag-node/blob/master/README.md#per-request-metadata.

Please let me know if this solves your problem

**Comment by mathieug** [comment]
@ConradIrwin thank you again.
Sometimes, bugsnag.requestData is undefined and my app crash if I don't do `bugsnag.requestData = bugsnag.requestData || {}`. Any idea?
