### ISSUE TITLE
Use requestData.userId instead of metaData.userId

### ISSUE THREAD

**Issue by mathieug** [bugsnag/bugsnag-node#54]
Would be nice if bugsnag uses `requestData.userId` instead of `metaData.userId`

**Comment by jessicard** [comment]
Hey @mathieug - It should already be doing that (see https://github.com/bugsnag/bugsnag-node/blob/master/lib/bugsnag.js#L42 & https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L25). Are you running into an issue?

**Comment by mathieug** [comment]
@jessicard Thank you, please see #55 for the exact issue.
