### ISSUE TITLE
requestData does not work

### ISSUE THREAD

**Issue by mathieug** [bugsnag/bugsnag-node#55]
```javascript
bugsnag.requestData = { userId: myUserObj.id, user: myUserObj };
```
This code does not work, on bugsnag the Tab custom is empty and New tab says:
![image](https://cloud.githubusercontent.com/assets/951183/6489775/7252e8b2-c2a1-11e4-8a82-fc211ea84ece.png)
Which is exactly what I'm doing.

**Comment by jessicard** [comment]
Hey @mathieug, thanks for the heads up! Sorry about the bug - I've created a PR for it here: https://github.com/bugsnag/bugsnag-node/pull/56

**Comment by mathieug** [comment]
@jessicard still not work with
```
      bugsnag.requestData = {
        userId: req.currentUser.id,
        user: req.currentUser
      };
```

**Comment by keeganlow** [comment]
Hey @mathieug, the data that you've added there should show up in the user tab. Is it not showing up for you? Could you link me to an error so I can take a look?
