### ISSUE TITLE
Errors context

### ISSUE THREAD

**Issue by mathieug** [bugsnag/bugsnag-node#57]
I use `bugsnag.notify()` in a file called logger.js:
```javascript
var bugsnag = require('bugsnag');

module.exports = {
  log: function() {
    // ...
    return console.log.apply(console, arguments);
  },

  info: function() {
    var message = Array.prototype.slice.call(arguments).join(' ');
    bugsnag.notify(message, { severity: 'info' });
    // ...
    return console.info(message);
  },

  warn: function() {
    var message = Array.prototype.slice.call(arguments).join(' ');
    bugsnag.notify(message, { severity: 'warning' });
    // ...
    return console.warn(message);
  },

  error: function() {
    var message = Array.prototype.slice.call(arguments).join(' ');
    bugsnag.notify(message, { severity: 'error' });
    // ...
    return console.error(message);
  }
};
```

This allows me to do some others actions when I need to report an error, a warning, ...
My issue is with the stacktrace sent to bugsnag, all the reported errors/warning/.. are stacked in `libs/logger.js`. How can I keep my source code DRY and get my reports accurate?

**Comment by snmaynard** [comment]
There are two ways that I can think of. One is to use the (onBeforeNotify)[https://github.com/bugsnag/bugsnag-node#onbeforenotify] to remove those stack lines from the reports. The second way is to provide a stack property that has already had the stack mutated to remove the logging stack lines. You could get a correctly formatted stack by copying a mutated new Error().stack into your error.

Do either of those work for you?

**Comment by mathieug** [comment]
Thanks. Can you gist me an example of the way with onBeforeNotify()?

**Comment by snmaynard** [comment]
You should be able to do it with,

```javascript
Bugsnag.onBeforeNotify(function(notification){
  if(notification.events[0].exceptions[0].stacktrace[0] == "path to file here") {
    notification.events[0].exceptions[0].stacktrace.shift()
  }
})
```

**Comment by kattrali** [comment]
Closing as fixed, can reopen if additional information needed.
