### ISSUE TITLE
Version Number was not changed for PR recently merged

### ISSUE THREAD

**Issue by QuentinDejean** [bugsnag/bugsnag-node#63]
Hi,

I raised a PR a few days ago that was just merged this morning.

Problem is that when trying to fetch the latest from NPM, it doesn't fetch the fix recently merged: I believe this is because the change hasn't been pushed to NPM itself, only to Github (see http://stackoverflow.com/a/23348036)

Is that possible for you guys to bump up the version of the package? 

I am asking that because I am currently using the winston-bugsnag package for my project, which is still pointing to bugsnag 1.6.5 which is failing for me.

Thanks guys!

**Comment by QuentinDejean** [comment]
Hi guys,

Any news on that?

Cheers

**Comment by jacobmarshall** [comment]
I think this can safely be closed now - latest version in NPM matches that of GitHub.

**Comment by snmaynard** [comment]
Thanks @jacobmarshall!
