### ISSUE TITLE
Add code support to node

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-node#65]
We should add support for code in stacktrace

**Comment by jacobmarshall** [comment]
I really want to have a look at implementing this - no promises on time. Is there anything that needs to be done on the server side in order to hook this up?

**Comment by jacobmarshall** [comment]
I assume it would work exactly the same way as the PHP notifier does - https://github.com/bugsnag/bugsnag-php/blob/dc2e0b6092806c59bd33ef6c6aa74332762ff659/src/Bugsnag/Stacktrace.php#L95?

**Comment by jacobmarshall** [comment]
PR coming later...

![screen shot 2015-11-05 at 1 21 16 pm](https://cloud.githubusercontent.com/assets/4710291/10956386/247d9dea-83c0-11e5-8675-481dc80b8093.png)
