### ISSUE TITLE
Reason for sending Cleaned Request Metadata 

### ISSUE THREAD

**Issue by CodeHex** [bugsnag/bugsnag-node#69]
In some cases, the cleaned request metadata is being added to node exceptions. 

https://github.com/bugsnag/bugsnag-node/search?utf8=%E2%9C%93&q=cleanedrequest

It is unclear why we add this data or what it represents. Is this feature complete?

**Comment by kattrali** [comment]
@snmaynard Should we yank this? I don't see what it is for either.

**Comment by snmaynard** [comment]
I think that cleaned request was set to prevent a recursion bug - we only wanted to save a certain amount on the domain. I think the bug is that this is appearing on people's dashboards, it should never appear in metadata.

**Comment by kattrali** [comment]
Potentially fixing this with #72, let me know if I missed anything here.
