### ISSUE TITLE
Node security advisory issued for bugsnag-node dependency dependency hawk

### ISSUE THREAD

**Issue by Jon-Biz** [bugsnag/bugsnag-node#71]
A node security advisory has been issued for `Hawk` versions < 3.1.3:

https://nodesecurity.io/advisories/77  

`Hawk` is an dependency of `Request`, which is dependency of this library, currently at version `2.53`. Hawk has been updated, and the latest version of `Request` will pick this fix up automatically:

https://github.com/request/request/issues/2020#issuecomment-173468959

**Comment by kattrali** [comment]
Thank you for the report, @Jon-Biz. Fixed by #70, shipping a release shortly.
