### ISSUE TITLE
It doesn't seem like the notify callback has any arguments

### ISSUE THREAD

**Issue by TylerBrock** [bugsnag/bugsnag-node#74]
The documentation says: "The callback has two arguments, err and response. The err argument will contain any error received when trying to send the notification, the response object will contain the response received from Bugsnag"

However when i provide a callback I the arguments are empty.

```js
bugsnag.notify(error, meta, function() {console.log('done', arguments)});
```

Output: `done {}`

**Comment by jacobmarshall** [comment]
It seems there are a few different places which the `callback` argument can be invoked.

It's possible for the function to be invoked without any arguments when the `Bugsnag.shouldNotify` function returns false, canceling the event from being sent to Bugsnag. See https://github.com/bugsnag/bugsnag-node/blob/master/lib/bugsnag.js#L94.

Other references are:
- https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L170
- https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L177
- https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L179

However in the process of tracking these references, I believe I have found a condition where the callback is not invoked at all. Which is where the library invokes the `beforeNotify` callbacks and allows them to prevent the event from being sent to Bugsnag. See https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L123.

@kattrali what are your thoughts on this? I would expect both https://github.com/bugsnag/bugsnag-node/blob/master/lib/bugsnag.js#L94 and https://github.com/bugsnag/bugsnag-node/blob/master/lib/notification.js#L123 to invoke the callback with an error as the first argument - as they both stop the event from being sent to Bugsnag.

I'm happy to submit a PR to fix these inconsistencies, and make a small alteration to the docs to explain this situation, if you'd like?

**Comment by kattrali** [comment]
Thank you for the report, @TylerBrock, and for the code dive, @jacobmarshall. I'll follow up with some feedback on #80.
