### ISSUE TITLE
support for HTTPS proxies

### ISSUE THREAD

**Issue by wprater** [bugsnag/bugsnag-node#76]
I cannot specify an HTTPS proxy url, not pass proxy auth headers.  These do not seem to be exposed in your implementation.  Do you have a recommended way, or do I need to open a PR?

**Comment by kattrali** [comment]
Hi @wprater, there is currently no implementation of using proxies for the node library, though a PR would be welcome. Existing implementations include [Ruby](https://github.com/bugsnag/bugsnag-ruby/blob/master/docs/Configuration.md#proxy_host) and [Python](https://github.com/bugsnag/bugsnag-python#proxy_host), if those could be of any help. Thanks!

**Comment by jacobmarshall** [comment]
You should be able to specify an HTTPS proxy url (https://github.com/bugsnag/bugsnag-node#proxy) as  `bugsnag-node` uses [`request`](https://www.npmjs.com/package/request#proxies) to send requests, which supports proxies, but what you are asking for is the ability to pass through proxy authorization details. Right?

If so, I'd be happy to submit a PR to support providing these details like so;

```js
bugsnag.register("your-api-key-here", {
    proxy: {
        url: "http://localhost:8080",
        auth: "XXX",
    },
});
```

Which behind the scenes would populate the `proxy-authorization` header to your proxy with the value of `proxy.auth`.
