### ISSUE TITLE
Express req.host deprecation

### ISSUE THREAD

**Issue by steebchen** [bugsnag/bugsnag-node#79]
There's a warning in bugsnag:

```
express deprecated req.host: Use req.hostname instead at ../node_modules/bugsnag/lib/request_info.js:6:63
```

Not important at all but I just wanted to let you know.

bugsnag@1.7.0
express@4.13.4

**Comment by jacobmarshall** [comment]
It seems that `req.host` is only used as a fallback if `req.hostname` is falsy. See https://github.com/bugsnag/bugsnag-node/blob/master/lib/request_info.js#L6.

**Comment by jacobmarshall** [comment]
Are you getting this error on a clean express setup? I ask because I wonder whether some middleware you're using is voiding `req.hostname`. Seems unlikely, but if you're using `express@4`, then `req.hostname` should absolutely be set.

**Comment by steebchen** [comment]
A middleware is probably the issue, because I double checked that I am using a new version of express (4.13.4). A clean express setup seems working but since I have dozens of middlewares in my production app (where I saw this warning in the logs) and I don't have a stacktrace this will be hard to find out.

**Comment by jacobmarshall** [comment]
Ah great. (Feel free to close this issue then 👍 )
