### ISSUE TITLE
Critical issue with filters

### ISSUE THREAD

**Issue by goldendase** [bugsnag/bugsnag-node#81]
Hi gang,

You have a pretty serious issue right here:

https://github.com/bugsnag/bugsnag-node/blob/master/lib/utils.js#L111

The issue here is that you're going to clobber data in the app using bugsnag-node. What you're doing there is an object reference lookup on the `object` belonging to the main app then modifying the data in that object. If the object going to bugsnag happens to be, say, a global singleton holding route definitions, and one of the routes is, for example, `password`, you will replace the entire object route definition with the string `'[FILTERED]'`. In the client app. Javascript is very much pass-by-reference when it comes to objects. I would suggest using something like this

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

instead, copying the object FIRST, then passing that *copy* to your service, rather than modifying data in the client app you're supposed to be monitoring. We just spent a couple of days trying to debug what was destroying our objects. A bug monitoring service is one of the last places we expected to find something like this.

As a random aside, I can't see why you would want to `process.exit()` as you do here:

https://github.com/bugsnag/bugsnag-node/blob/master/lib/configuration.js#L29

That seems totally crazy. If an unhandled exception happens, you terminate my server process? For a notification / monitoring library, you sure are taking some liberties with the execution of the thing you're supposed to be monitoring. Rule #1 should be "don't alter the thing you're supposed to be monitoring".

Thanks!
Peter

**Comment by kattrali** [comment]
Thank you for the report, @goldendase. The filters issues is fixed via #82. I'll take a look into the other one shortly.
