### ISSUE TITLE
Please document whether `bugsnag.notify` is sync or async

### ISSUE THREAD

**Issue by markstos** [bugsnag/bugsnag-node#84]
The docs should clarify whether `bugsnag.notify` is sync or async if no callback used. 

This matters because that happens just after calling `bugsnag.crash` may cause a crash. If it happens fast enough, the Bugsnag notification might not get through.

**Comment by kattrali** [comment]
Thanks for the report, @markstos! I’ll look into updating the docs.

**Comment by kattrali** [comment]
I’ve updated the guide on [Reporting handled errors](https://docs.bugsnag.com/platforms/nodejs/other/reporting-handled-errors/) to be clearer about the behavior of `bugsnag.notify` and that delivery is asynchronous. Thanks again!
