### ISSUE TITLE
require.main.filename isn't always available

### ISSUE THREAD

**Issue by joshunger** [bugsnag/bugsnag-node#85]
require.main.filename isn't always available.  Can you detect if it is undefined and not use it?

See https://github.com/bugsnag/bugsnag-node/blob/master/lib/configuration.js

Something like - 
`projectRoot: require.main !== undefined && require.main.filename !== undefined ?path.dirname(require.main.filename) : null`

It is undefined if I'm using webpack to bundle my server side code.

**Comment by kattrali** [comment]
Thanks for the report, I’ll take a look at a patch
