### ISSUE TITLE
Exposing middlewares as factories

### ISSUE THREAD

**Issue by jonathansamines** [bugsnag/bugsnag-node#87]
I just was wonder if it was possible to expose the `bugsnag middleware` handler functions as factories. Basically the change would imply to use the middlewares by calling a function:

``` js
    const express = require('express');
    const bugsnag = require('bugsnag');
    const app = express();

    app.use(bugsnag.requestHandler(options));
    app.use(bugsnag.errorHandler(options));
```

The change seems quite simple, but would help to use this module along with modules like https://github.com/krakenjs/meddleware and generally load middlewares by just using configuration. That change would require to also try to register the bugsnag middleware along with each of the handlers.

**Comment by kattrali** [comment]
Thanks for the suggestion, @jonathansamines. That sounds like a fairly simple change, and it would be useful for configuring handlers before initialization. The names would need to be different from the existing handlers for compatibility reasons though, and to hopefully reduce confusion. Maybe something like `bugsnag.createRequestHandler(options)` ?

**Comment by jonathansamines** [comment]
Hi @kattrali seems like a good name for its purpose. Is there something I can help with?

**Comment by kattrali** [comment]
@jonathansamines Sure, feel free to make a PR and we can discuss further. Let me know if you have questions!

**Comment by bullmo** [comment]
@jonathansamines Version 1.9.0 of the node notifier has now been released with the middleware factory changes that you made in https://github.com/bugsnag/bugsnag-node/pull/88. Thanks for adding that.

**Comment by jonathansamines** [comment]
Thanks, sorry for not adding the tests. I completely forgot about this feature, but glad to hear was already published :)
