### ISSUE TITLE
Promises are ignored by default

### ISSUE THREAD

**Issue by steebchen** [bugsnag/bugsnag-node#89]
While uncaught exceptions are always caught, uncaught rejected promises are ignored. Wouldn't it be extremely useful if Bugsnag would handle them too? In production, I encountered an issue where I didn't catch a rejection and got a timeout instead – and saw nothing in my bugsnag dashboard. I am now listening on process.unhandledRejection, but it would be useful if bugsnag-node could do that automatically.

**Comment by kattrali** [comment]
That makes a lot of sense, @steebchen. I think the biggest issue would be the different implementations of promises used, and perhaps the node version, but this is definitely something the library should attempt to do automatically.

**Comment by bengourley** [comment]
Now that promises are in core and lots of promise libraries will _probably_ default to using native promises if available, there should be enough usage that listening to `'unhandledRejection'` is worthwhile.

The only thing to be aware of is the side-effect(s) of attaching a listener to the `'unhandledException'` and `'unhandledRejection'` events. Currently the former prevents the default behaviour (which is to log the error and exit with a non-zero code) and the latter doesn't, but this is planned to change:

```
Development/scratch » node unhandled.js
(node:7478) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: :(
(node:7478) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
