### ISSUE TITLE
Reporting not working from Webpack bundled code (Blank version number)

### ISSUE THREAD

**Issue by JoeStanton** [bugsnag/bugsnag-node#90]
I have no idea if Lambda is related, but deliberately causing an error and having it handled by `bugsnag.notify(e)` in a try/catch leads to the following payload:

```
{
  "apiKey":"REDACTED",
  "notifier":{
    "name":"Bugsnag Node Notifier",
    "version":null,
    "url":"https://github.com/bugsnag/bugsnag-node"
  },
  "events":[
    {
      "exceptions":[
        {
          "message":"testRef is not defined",
          "errorClass":"ReferenceError",
          "stacktrace":[
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"none",
              "lineNumber":53620,
              "columnNumber":13
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"tryCatcher",
              "lineNumber":836,
              "columnNumber":24
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_settlePromiseFromHandler",
              "lineNumber":62551,
              "columnNumber":32
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_settlePromise",
              "lineNumber":62608,
              "columnNumber":19
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_settlePromise0",
              "lineNumber":62653,
              "columnNumber":11
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_settlePromises",
              "lineNumber":62732,
              "columnNumber":19
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_drainQueue",
              "lineNumber":59684,
              "columnNumber":17
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"_drainQueues",
              "lineNumber":59694,
              "columnNumber":11
            },
            {
              "file":"/var/task/index.js",
              "path":"/var/task/index.js",
              "method":"Async.drainQueues [as _onImmediate]",
              "lineNumber":59563,
              "columnNumber":15
            },
            {
              "file":"timers.js",
              "path":"timers.js",
              "method":"processImmediate [as _immediateCallback]",
              "lineNumber":383,
              "columnNumber":17
            }
          ]
        }
      ],
      "metaData":{

      },
      "releaseStage":"production",
      "payloadVersion":"2",
      "severity":"warning",
      "device":{
        "hostname":"ip-10-13-79-136"
      }
    }
  ]
}
```

This is received as a 200 OK by Bugsnag (which I understand to just mean queued, not processed). This exception never actually appears in the UI.

Do we have a way to validate the payload?

**Comment by kattrali** [comment]
Thanks for the report, @JoeStanton. At first glance, I'd think it would be something to do with the `notifier` section having a null `version` field, but we'll look into it.

**Comment by wordofchristian** [comment]
I've setup a new lambda server to test this and was able to report errors to bugsnag just fine. Perhaps there is some environment difference that is preventing it from working for you.

Essentially all we are doing to get the version number is:
```js
var path = require('path');
require(path.join(__dirname, '..', 'package.json')).version;
```
I suppose it's possible that there's a problem with `__dirname`?

Can you confirm that `__dirname` is working on your lambda server?

**Comment by JoeStanton** [comment]
Thanks for looking into this - I've cracked it. As we're transpiling ES6/7, we produce a Webpack bundle that we then use on Lambda. I know this is a little bit uncommon for server side code. 

Because your version lookup depends on the directory structure, it fails in this context.

Would you recommend if we're producing a JS bundle that we use the client side JS version of this library?

**Comment by wordofchristian** [comment]
No, the client side JS version is only meant to work inside a browser environment. According to [this thread](https://github.com/webpack/webpack/issues/603) you can try listing bugsnag in externals under your webpack config.

 If that doesn't work, then maybe we can add something to the library to detect that it is being processed by webpack and require the package.json rather than reading it from disk.

**Comment by JoeStanton** [comment]
If we list Bugsnag as a webpack external, users will need to do additional work to ensure this file is shipped next to their bundle and made available by some other means.

IMO it would be preferable to follow your latter suggestion on this? It may be an edge case, but I don't think its safe to assume runtime paths in the age of bundling, and this is non-trivial to debug when it does happen.

**Comment by jacobmarshall** [comment]
It looks to me as if your patch, @JoeStanton (https://github.com/redbadger/bugsnag-node/commit/d877e32aab8b7d507ed3b66cd487e3d3b137dcd1) is enough to support both standard (non-transpiled) node.js apps, and bundled node.js apps as well. Or am I wrong?

From what I can tell `Utils.getPackageVersion` does a simple `require` anyway, so there's little to no difference - other than the relative path.

If that's correct, would it not be as simple as merging that patch upstream?

**Comment by JoeStanton** [comment]
@jacobmarshall it is indeed sufficient for bundled/non-bundled node apps, however, it assumes the existence of `package.json` without a `try/catch`. It would be quite odd for this file not to exist, but not sure if this would break someones use case.

**Comment by jacobmarshall** [comment]
> @jacobmarshall it is indeed sufficient for bundled/non-bundled node apps, however, it assumes the existence of package.json without a try/catch. It would be quite odd for this file not to exist, but not sure if this would break someones use case.

Correct, because it's reading the `bugsnag-node` `package.json` file. Which should always be picked up from the module bundler - in this case webpack.

I'll be honest, it's kind of strange to me that the current code wraps the `require` in a `try/catch`. I can see that it's always been there (https://github.com/bugsnag/bugsnag-node/commit/c5aaa5f1cce320036817a6fa61aec7ed4c17d694) - but I'm fairly confident it doesn't need to be there.

**Comment by jacobmarshall** [comment]
> I'll be honest, it's kind of strange to me that the current code wraps the require in a try/catch. I can see that it's always been there (c5aaa5f) - but I'm fairly confident it doesn't need to be there.

I can see now that it's also used to pickup the app's `package.json` version if one is not provided in `Configuration.appVersion` (https://github.com/bugsnag/bugsnag-node/blob/master/lib/configuration.js#L69). So that explains it 😜

**Comment by kattrali** [comment]
Hardcoding this value is the simple solution, and the same as other bugsnag libraries. I updated the release instructions as well as the value to ensure it stays up to date.
